# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zhuwannian.github.io
date_format: "ordinal"
title: 立刻有
subtitle: "立刻有"
description: "朱万年的个人博客"
keywords: 立刻有, Wannian Zhu, zwnlogin, zhuwannian
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wannian Zhu
organization: zkh360.com
organization_url: http://www.zkh360.com
github_username: zhuwannian
location: Beijing, China
email: zhu_wannian@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhuwannian
    repo: blog-comments
    oauth:
        client_id: 51371cd69d291c3816f7
        client_secret: f34271cb0eb8bac24c5a2df8ae2ad18e1109b8c5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhuwannian
    repo: blog-comments
    clientID: 51371cd69d291c3816f7
    clientSecret: f34271cb0eb8bac24c5a2df8ae2ad18e1109b8c5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
